<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(Configuration)' == 'Release'">true</ContinuousIntegrationBuild>
    <AnalysisLevel>latest</AnalysisLevel>
    <Version>0.5.2</Version>
    <Authors>DIGA contributors</Authors>
    <Copyright>Copyright © 2026 DIGA contributors</Copyright>
  </PropertyGroup>
</Project>
